apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: frontend-api
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: frontend-api
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
