apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-api
  labels:
    app: frontend-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 30%
  selector:
    matchLabels:
      app: frontend-api
  template:
    metadata:
      labels:
        app: frontend-api
    spec:
      terminationGracePeriodSeconds: 35
      containers:
        - name: frontend-api
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10G"
              cpu: "2"
            limits:
              memory: "10G"
              cpu: "4"
          envFrom:
            - secretRef:
                name: frontend-api
            - configMapRef:
                name: frontend-api
