apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: react
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 30%
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      terminationGracePeriodSeconds: 35
      containers:
        - name: react
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10G"
              cpu: "2"
            limits:
              memory: "10G"
              cpu: "4"
          envFrom:
            - secretRef:
                name: react
            - configMapRef:
                name: react
